'''
Created on 08/dic/2010

@author: tosh
'''
from pygame.locals import *

FONT_PATH = "../font/"
SND_PATH = "../snd/"

# FRASI DETTE DAI NEMICI
K_EN_SENTENCES = ("YOUR MOM IS A TRIANGLE!", "I WANNA KILL U", 
                  "LET ME TOUCH YOU", "I LOVE ABBOT", "FLATLAND, MY LOVE",
                  "PUTTING U DOWN", "MEH!?")
K_EN_SINUSOIDAL_SENT = K_EN_SENTENCES + ("SIN > COS !!", "WE <3 SIN")

# Costanti
M_NORTH = 0
M_WEST = 1
M_SOUTH = 2
M_EAST = 3
K_MOV = 5

K_TICK = 30

K_ENEMY_MOV = 4
K_BULLET_SPEED = 15 # BULLET SPEED IN PIXEL
K_COOLDOWN = 5
K_GOODIE_COOLDOWN = 2 * K_TICK
K_JUNKIE_RADIUS = 60
K_JUNK_MOV = 3
K_BOX_DIMENSION = (15, 15)
K_BULLET_DIMENSION = (5,3)
K_JUNK_DIMENSION = (3,3)
K_WINDOW_DIM = (640,320)
K_HP = 3
K_FONT_COLOR = (0,0,0)
K_FONT = FONT_PATH + "drid.ttf"
K_GOODIE_FONT = None
K_BALOON_FONT = FONT_PATH + "bitlow.ttf"
K_GOODIE_FONT_DIM = 15
K_LEVEL = 1


# NUMERO STANDARD DI COLPI
K_FAN_AMMO = 20
K_TRIPLE_AMMO = 30
K_BEAM_AMMO = 3

# PUNTI UCCISIONE
K_ENEMY_BOX_PT = 100
K_ENEMY_SIN = 150


# GRUPPI TASTI
M_DOWN = [K_DOWN]
M_UP = [K_UP]
M_RIGHT = [K_RIGHT]
M_LEFT = [K_LEFT]
M_WEAPON_SHOOT = [K_d]
M_PAUSE = [K_SPACE]
M_EXIT = [K_ESCAPE]
