'''
Created on 08/dic/2010

@author: tosh
'''
# Costanti
M_NORTH = 0
M_WEST = 1
M_SOUTH = 2
M_EAST = 3
K_MOV = 8
K_ENEMY_MOV = 2
K_LEVEL = 10 # BULLET SPEED IN PIXEL
K_COOLDOWN = 5
K_JUNKIE_RADIUS = 60
K_JUNK_MOV = 3
K_BOX_DIMENSION = (15, 15)
K_BULLET_DIMENSION = (5,3)
K_JUNK_DIMENSION = (3,3)
K_WINDOW_DIM = (640,320)